### ISSUE TITLE
Error should be raised if a plugin  is specified in `plugins` but not configured 

### ISSUE THREAD

**Issue by Thirdegree** [optiver/vulcan-py#20]
i.e. if you have 

```toml
[tool.vulcan]
plugins=["foobar"]

```
but not

```toml
[tool.vulcan.plugin.foobar]
```

That should be an error.
